#ifndef MAP_SHORTEST_PATH_COMMON_H
#define MAP_SHORTEST_PATH_COMMON_H

#define MSP_MAX_NODES 256
#define MSP_MAX_EDGES 2048
#define MSP_MAX_PLACES 128
#define MSP_MAX_GEOMETRY_POINTS 1024
#define MSP_NAME_LENGTH 64
#define MSP_CATEGORY_LENGTH 32
#define MSP_EXTERNAL_ID_LENGTH 16
#define MSP_LINE_LENGTH 512
#define MSP_INFINITY 1.0e100
#define MSP_EPSILON 1.0e-9

typedef enum {
    MSP_OK = 0,
    MSP_ERROR_INVALID_ARGUMENT = -1,
    MSP_ERROR_CAPACITY = -2,
    MSP_ERROR_DUPLICATE = -3,
    MSP_ERROR_NOT_FOUND = -4,
    MSP_ERROR_IO = -5,
    MSP_ERROR_FORMAT = -6,
    MSP_ERROR_NO_PATH = -7
} MspStatus;

#endif
