#ifndef MAP_SHORTEST_PATH_UI_TEXT_H
#define MAP_SHORTEST_PATH_UI_TEXT_H

typedef enum {
    UI_WINDOW_TITLE = 0,
    UI_BRAND,
    UI_TITLE,
    UI_START,
    UI_START_HINT,
    UI_DESTINATION,
    UI_DESTINATION_HINT,
    UI_ROUTE_MODE,
    UI_START_NAVIGATION,
    UI_CHOOSE_ROUTE,
    UI_CHOOSE_BOTH,
    UI_SAME_ENDPOINT,
    UI_PLANNING_ROUTE,
    UI_NO_ROUTE,
    UI_ROUTE_READY,
    UI_PRESS_START,
    UI_ROUTE_CLEARED,
    UI_ROUTE_DETAILS,
    UI_ROUTE_DETAILS_HINT,
    UI_DISTANCE_UNIT,
    UI_DISTANCE_UNIT_GENERIC,
    UI_ROUTE,
    UI_SEARCH_HINT,
    UI_MAP_LEGEND,
    UI_LEGEND_TEACHING,
    UI_LEGEND_DORM_DINING,
    UI_LEGEND_GREEN,
    UI_LEGEND_WATER,
    UI_LEGEND_ROAD,
    UI_LEGEND_ROUTE
} UiTextId;

const char *ui_text(UiTextId id);
const char *ui_place_name(const char *internal_name);
const char *ui_font_glyphs(void);

#endif
